name: Mirror __mirror_to_public_repo to public repo

on:
  push: 
    branches: [ __mirror_to_public_repo ]
    
permissions:
  contents: read

env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  PUBLIC_REPO: vl-test-mirror
  OWNER: ${{ github.repository_owner }}
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          ref: __mirror_to_public_repo
          fetch-depth: 0
      - name: Push __mirror_to_public_repo to main
        env:
            PAT: ${{ secrets.PAT_TOKEN }}
            PUBLIC_REPO_OWNER: ${{ github.repository_owner }}
            PUBLIC_REPO_NAME: vl-test-mirror
        run: |
          git config user.name  "mirror-bot"
          git config user.email "mirror-bot@users.noreply.github.com"

          git push -f \
            "https://${{ env.PUBLIC_REPO_OWNER }}:${{ env.PAT }}@github.com/${{ env.PUBLIC_REPO_OWNER }}/${{ env.PUBLIC_REPO_NAME }}" \
            __mirror_to_public_repo:main
