name: Mirror __mirror_to_public_repo to public repo

on:
  push: 
    branches: [ __mirror_to_public_repo ]
    
permissions:
  contents: read

env:
  PUBLIC_REPO: vl-test-mirror
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
jobs:
  test_pat:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PAT_TOKEN secret exists
        env:
          # Pass the secret into a job environment variable
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          if [ -n "$PAT" ]; then
            # If the variable is NOT zero length (-n), it loaded successfully
            echo "✅ Success: The PAT was loaded (length: ${#PAT} characters)."
          else
            # If the variable IS zero length, it failed to load
            echo "❌ Failure: The PAT variable is empty."
            exit 1
          fi
  mirror:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          ref: __mirror_to_public_repo
          fetch-depth: 0
      - name: Push __mirror_to_public_repo to main
        env:
            PUBLIC_REPO_NAME: vl-test-mirror
        run: |
          git config user.name  "qcdis-bot"
          git config user.email "qcdis-bot@users.noreply.github.com"

          git push -f \
            "https://x-access-token:${{ env.PAT_TOKEN }}@github.com/${{ github.repository_owner }}/${{ env.PUBLIC_REPO_NAME }}".git \
            __mirror_to_public_repo:main
