name: Mirror __mirror_to_public_repo to public repo

on:
  push: 
    branches: [ __mirror_to_public_repo ]
    
permissions:
  contents: read

env:
  PUBLIC_REPO: vl-test-mirror
  PAT: ${{ secrets.PAT_VL_TEST_MIRROR }}
jobs:
  test_pat:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PAT secret exists
        run: |
          if [ -n "$PAT" ]; then
            # If the variable is NOT zero length (-n), it loaded successfully
            echo "✅ Success: The PAT was loaded (length: ${#PAT} characters)."
          else
            # If the variable IS zero length, it failed to load
            echo "❌ Failure: The PAT variable is empty."
            exit 1
          fi
      - name: Test Authentication to Target Repo (Dry Run)
        run: |
          # Use 'git ls-remote' to test read authentication without pushing any data
          # This should succeed if the PAT has read access.
          git ls-remote "https://x-access-token:${{ env.PAT }}@github.com/${{ github.repository_owner }}/${{ env.PUBLIC_REPO }}.git"
          
          echo "✅ Authentication test passed. The PAT is connecting successfully."
  test_fail_pat:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PAT secret exists
        run: |
          if [ -n "$FOOTPAT" ]; then
            echo "❌ Failure: The FOOTPAT is a variable."
          else
            echo "✅ Success: The FOOTPAT doesn't exist."
          fi
      - name: Test Authentication to Target Repo (Dry Run) - expecting failure
        run: |
          # Use 'git ls-remote' to test read authentication without pushing any data
          # This should succeed if the PAT has read access.
          git ls-remote "https://x-access-token:${{ env.NONEXISTENTPAT }}@github.com/${{ github.repository_owner }}/${{ env.PUBLIC_REPO }}.git"
          
          echo "✅ Authentication test passed. The PAT is connecting successfully."
  mirror:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          ref: __mirror_to_public_repo
          fetch-depth: 0
      - name: Push __mirror_to_public_repo to main
        run: |
          git config user.name  "qcdis-bot"
          git config user.email "qcdis-bot@users.noreply.github.com"

          git push -f "https://x-access-token:${{ env.PAT }}@github.com/naavre/${{ env.PUBLIC_REPO }}.git" __mirror_to_public_repo:main
